/* Lista de precios ficticia de Distribuidora Ruta 9. Marcas, códigos y precios inventados (sin IVA). */

export type Rubro = "almacen" | "bebidas" | "limpieza" | "perfumeria" | "descartables";
export type Stock = "ok" | "bajo" | "sin";

export type Articulo = {
  id: string;
  nombre: string;
  marca: string;
  rubro: Rubro;
  presentacion: string;
  /** Unidades por bulto. */
  bulto: number;
  precio: number;
  /** Precio anterior por unidad, si está en oferta. */
  antes?: number;
  stock: Stock;
  variantes?: string[];
  nuevo?: boolean;
};

export const RUBROS: { id: Rubro; nombre: string }[] = [
  { id: "almacen", nombre: "Almacén" },
  { id: "bebidas", nombre: "Bebidas" },
  { id: "limpieza", nombre: "Limpieza" },
  { id: "perfumeria", nombre: "Perfumería e higiene" },
  { id: "descartables", nombre: "Descartables" },
];

export const PEDIDO_MINIMO = 150000;

export const EMPRESA = {
  nombre: "Distribuidora Ruta 9",
  atencion: "Lunes a viernes de 7 a 16 h",
  entregas: "Martes y viernes en Córdoba capital y Gran Córdoba",
  actualizada: "Lista de precios actualizada el 29/09",
};

export const ARTICULOS: Articulo[] = [
  {
    id: "al-1001",
    nombre: "Fideos tirabuzón",
    marca: "Doña Clara",
    rubro: "almacen",
    presentacion: "500 g",
    bulto: 20,
    precio: 1150,
    stock: "ok",
  },
  {
    id: "al-1002",
    nombre: "Fideos spaghetti",
    marca: "Doña Clara",
    rubro: "almacen",
    presentacion: "500 g",
    bulto: 20,
    precio: 1150,
    stock: "ok",
  },
  {
    id: "al-1010",
    nombre: "Arroz largo fino",
    marca: "Campo Alto",
    rubro: "almacen",
    presentacion: "1 kg",
    bulto: 10,
    precio: 1890,
    stock: "ok",
  },
  {
    id: "al-1015",
    nombre: "Harina de trigo 000",
    marca: "Molino Serrano",
    rubro: "almacen",
    presentacion: "1 kg",
    bulto: 10,
    precio: 980,
    stock: "ok",
  },
  {
    id: "al-1016",
    nombre: "Azúcar común tipo A",
    marca: "Dulzura",
    rubro: "almacen",
    presentacion: "1 kg",
    bulto: 10,
    precio: 1320,
    stock: "ok",
  },
  {
    id: "al-1020",
    nombre: "Yerba mate con palo",
    marca: "La Tranquera",
    rubro: "almacen",
    presentacion: "1 kg",
    bulto: 10,
    precio: 4650,
    antes: 4990,
    stock: "ok",
  },
  {
    id: "al-1021",
    nombre: "Yerba mate suave",
    marca: "La Tranquera",
    rubro: "almacen",
    presentacion: "500 g",
    bulto: 20,
    precio: 2480,
    stock: "ok",
  },
  {
    id: "al-1030",
    nombre: "Aceite de girasol",
    marca: "Olivar del Sur",
    rubro: "almacen",
    presentacion: "1,5 L",
    bulto: 12,
    precio: 3950,
    antes: 4290,
    stock: "ok",
  },
  {
    id: "al-1040",
    nombre: "Puré de tomate",
    marca: "Huerta Fina",
    rubro: "almacen",
    presentacion: "520 g",
    bulto: 12,
    precio: 890,
    stock: "ok",
  },
  {
    id: "al-1041",
    nombre: "Tomate perita entero",
    marca: "Huerta Fina",
    rubro: "almacen",
    presentacion: "Lata 400 g",
    bulto: 24,
    precio: 1240,
    stock: "ok",
  },
  {
    id: "al-1042",
    nombre: "Arvejas secas remojadas",
    marca: "Huerta Fina",
    rubro: "almacen",
    presentacion: "Lata 350 g",
    bulto: 24,
    precio: 790,
    stock: "ok",
  },
  {
    id: "al-1050",
    nombre: "Galletitas de agua",
    marca: "Crocante",
    rubro: "almacen",
    presentacion: "3 × 100 g",
    bulto: 24,
    precio: 1380,
    stock: "ok",
  },
  {
    id: "al-1051",
    nombre: "Galletitas dulces",
    marca: "Crocante",
    rubro: "almacen",
    presentacion: "150 g",
    bulto: 30,
    precio: 1090,
    stock: "ok",
    variantes: ["Vainilla", "Chocolate", "Limón"],
  },
  {
    id: "al-1060",
    nombre: "Dulce de leche clásico",
    marca: "Pradera Mansa",
    rubro: "almacen",
    presentacion: "Frasco 400 g",
    bulto: 12,
    precio: 2750,
    stock: "bajo",
  },
  {
    id: "al-1061",
    nombre: "Mayonesa clásica",
    marca: "Doña Clara",
    rubro: "almacen",
    presentacion: "Doypack 475 g",
    bulto: 20,
    precio: 1690,
    stock: "ok",
  },
  {
    id: "al-1070",
    nombre: "Café molido torrado",
    marca: "Tostadero",
    rubro: "almacen",
    presentacion: "250 g",
    bulto: 12,
    precio: 4200,
    stock: "ok",
    nuevo: true,
  },
  {
    id: "al-1071",
    nombre: "Té negro en saquitos",
    marca: "Brote",
    rubro: "almacen",
    presentacion: "Caja × 25",
    bulto: 24,
    precio: 1150,
    stock: "ok",
  },
  {
    id: "al-1080",
    nombre: "Leche entera larga vida",
    marca: "Pradera Mansa",
    rubro: "almacen",
    presentacion: "1 L",
    bulto: 12,
    precio: 1480,
    stock: "ok",
  },
  {
    id: "be-2001",
    nombre: "Gaseosa cola",
    marca: "Burbuja",
    rubro: "bebidas",
    presentacion: "2,25 L",
    bulto: 8,
    precio: 2980,
    stock: "ok",
  },
  {
    id: "be-2002",
    nombre: "Gaseosa lima limón",
    marca: "Burbuja",
    rubro: "bebidas",
    presentacion: "2,25 L",
    bulto: 8,
    precio: 2750,
    stock: "ok",
  },
  {
    id: "be-2003",
    nombre: "Gaseosa naranja",
    marca: "Burbuja",
    rubro: "bebidas",
    presentacion: "1,5 L",
    bulto: 8,
    precio: 2150,
    stock: "ok",
  },
  {
    id: "be-2010",
    nombre: "Agua mineral sin gas",
    marca: "Manantial",
    rubro: "bebidas",
    presentacion: "2 L",
    bulto: 6,
    precio: 1050,
    stock: "ok",
  },
  {
    id: "be-2011",
    nombre: "Agua mineral con gas",
    marca: "Manantial",
    rubro: "bebidas",
    presentacion: "1,5 L",
    bulto: 6,
    precio: 990,
    stock: "ok",
  },
  {
    id: "be-2030",
    nombre: "Cerveza rubia lata",
    marca: "Cumbre",
    rubro: "bebidas",
    presentacion: "473 ml",
    bulto: 24,
    precio: 1690,
    antes: 1850,
    stock: "ok",
  },
  {
    id: "be-2031",
    nombre: "Cerveza negra lata",
    marca: "Cumbre",
    rubro: "bebidas",
    presentacion: "473 ml",
    bulto: 24,
    precio: 1790,
    stock: "bajo",
  },
  {
    id: "be-2040",
    nombre: "Vino tinto de mesa",
    marca: "Viña Brava",
    rubro: "bebidas",
    presentacion: "Tetra 1 L",
    bulto: 12,
    precio: 1890,
    stock: "ok",
  },
  {
    id: "be-2041",
    nombre: "Jugo listo",
    marca: "Frutal",
    rubro: "bebidas",
    presentacion: "Tetra 1 L",
    bulto: 12,
    precio: 1290,
    stock: "ok",
    variantes: ["Durazno", "Naranja", "Multifruta"],
  },
  {
    id: "li-3001",
    nombre: "Lavandina concentrada",
    marca: "Brillo Sur",
    rubro: "limpieza",
    presentacion: "1 L",
    bulto: 12,
    precio: 890,
    antes: 990,
    stock: "ok",
  },
  {
    id: "li-3002",
    nombre: "Lavandina concentrada",
    marca: "Brillo Sur",
    rubro: "limpieza",
    presentacion: "Bidón 5 L",
    bulto: 4,
    precio: 3690,
    stock: "ok",
  },
  {
    id: "li-3010",
    nombre: "Detergente limón",
    marca: "Brillo Sur",
    rubro: "limpieza",
    presentacion: "750 ml",
    bulto: 12,
    precio: 1180,
    stock: "ok",
  },
  {
    id: "li-3020",
    nombre: "Jabón en polvo",
    marca: "Espuma Real",
    rubro: "limpieza",
    presentacion: "800 g",
    bulto: 12,
    precio: 3450,
    stock: "ok",
  },
  {
    id: "li-3021",
    nombre: "Jabón líquido para ropa",
    marca: "Espuma Real",
    rubro: "limpieza",
    presentacion: "Bidón 3 L",
    bulto: 4,
    precio: 8900,
    stock: "ok",
    nuevo: true,
  },
  {
    id: "li-3030",
    nombre: "Suavizante para ropa",
    marca: "Nube",
    rubro: "limpieza",
    presentacion: "Doypack 900 ml",
    bulto: 12,
    precio: 1980,
    stock: "ok",
    variantes: ["Clásico", "Primaveral"],
  },
  {
    id: "li-3040",
    nombre: "Limpiador de pisos",
    marca: "Aroma Hogar",
    rubro: "limpieza",
    presentacion: "900 ml",
    bulto: 12,
    precio: 1450,
    stock: "ok",
    variantes: ["Lavanda", "Pino", "Marina"],
  },
  {
    id: "pe-4001",
    nombre: "Papel higiénico hoja simple",
    marca: "Pulcra",
    rubro: "perfumeria",
    presentacion: "4 rollos × 30 m",
    bulto: 12,
    precio: 2350,
    stock: "ok",
  },
  {
    id: "pe-4002",
    nombre: "Rollo de cocina",
    marca: "Pulcra",
    rubro: "perfumeria",
    presentacion: "3 rollos",
    bulto: 12,
    precio: 2690,
    stock: "ok",
  },
  {
    id: "pe-4010",
    nombre: "Jabón de tocador",
    marca: "Espuma Real",
    rubro: "perfumeria",
    presentacion: "90 g",
    bulto: 48,
    precio: 690,
    stock: "ok",
    variantes: ["Rosa mosqueta", "Avena", "Coco"],
  },
  {
    id: "pe-4020",
    nombre: "Shampoo nutritivo",
    marca: "Raíz",
    rubro: "perfumeria",
    presentacion: "350 ml",
    bulto: 12,
    precio: 3150,
    stock: "sin",
  },
  {
    id: "pe-4030",
    nombre: "Crema dental menta",
    marca: "Menta Clara",
    rubro: "perfumeria",
    presentacion: "90 g",
    bulto: 12,
    precio: 1590,
    stock: "ok",
  },
  {
    id: "de-5001",
    nombre: "Servilletas de papel",
    marca: "Pulcra",
    rubro: "descartables",
    presentacion: "33 × 33 cm × 100",
    bulto: 24,
    precio: 1290,
    stock: "ok",
  },
  {
    id: "de-5010",
    nombre: "Bolsas de residuo",
    marca: "Fuerte",
    rubro: "descartables",
    presentacion: "50 × 70 cm × 10",
    bulto: 20,
    precio: 1490,
    stock: "ok",
  },
];

export const ARTICULO_POR_ID = new Map(ARTICULOS.map((a) => [a.id, a]));

export const MARCAS = [...new Set(ARTICULOS.map((a) => a.marca))].sort((a, b) => a.localeCompare(b, "es"));

export const codigo = (id: string) => id.toUpperCase();
export const imagen = (id: string) => `/demos/catalogos/mayorista/${id}.webp`;
export const precioBulto = (a: Articulo) => a.precio * a.bulto;
