import type { ConfigTienda, ProductoCarrito } from "../shared/tipos";

export type Categoria = "Auriculares" | "Parlantes" | "Notebooks" | "Celulares" | "Relojes" | "Tablets" | "Accesorios";
export type Marca = "Nodo" | "Kairo" | "Sónica" | "Vektra";

export type ProductoTech = ProductoCarrito & {
  marca: Marca;
  categoria: Categoria;
  precioAnterior?: number;
  rating: number;
  opiniones: number;
  stock: boolean;
  /** Días hábiles de entrega estándar. */
  entrega: number;
  destacados: string[];
  specs: [string, string][];
  caja: string[];
};

const img = (n: string) => `/demos/ecommerce/tech-store/${n}.webp`;

export const productos: ProductoTech[] = [
  {
    id: "onda-700",
    nombre: "Nodo Onda 700",
    marca: "Nodo",
    categoria: "Auriculares",
    precio: 189999,
    precioAnterior: 219999,
    imagen: img("auriculares-onda-grafito"),
    alt: "Auriculares over-ear color grafito con almohadillas acolchadas",
    detalle: "Grafito",
    rating: 4.7,
    opiniones: 318,
    stock: true,
    entrega: 1,
    destacados: ["ANC híbrida", "40 h", "BT 5.3"],
    specs: [
      ["Tipo", "Over-ear inalámbricos"],
      ["Cancelación de ruido", "Activa híbrida"],
      ["Batería", "40 h"],
      ["Carga rápida", "10 min = 5 h"],
      ["Conexión", "Bluetooth 5.3 multipunto"],
      ["Peso", "254 g"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Auriculares", "Estuche rígido", "Cable USB-C", "Adaptador de avión"],
  },
  {
    id: "pulse",
    nombre: "Sónica Pulse",
    marca: "Sónica",
    categoria: "Auriculares",
    precio: 129999,
    imagen: img("auriculares-pulse-blanco"),
    alt: "Auriculares over-ear blancos",
    detalle: "Blanco",
    rating: 4.4,
    opiniones: 142,
    stock: false,
    entrega: 3,
    destacados: ["ANC", "30 h", "220 g"],
    specs: [
      ["Tipo", "Over-ear inalámbricos"],
      ["Cancelación de ruido", "Activa"],
      ["Batería", "30 h"],
      ["Carga rápida", "10 min = 3 h"],
      ["Conexión", "Bluetooth 5.2"],
      ["Peso", "220 g"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Auriculares", "Funda de tela", "Cable USB-C"],
  },
  {
    id: "air-buds",
    nombre: "Kairo Air Buds 2",
    marca: "Kairo",
    categoria: "Auriculares",
    precio: 99999,
    imagen: img("buds-air-blanco"),
    alt: "Auriculares in-ear blancos en su estuche de carga abierto",
    detalle: "Blanco",
    rating: 4.6,
    opiniones: 511,
    stock: true,
    entrega: 1,
    destacados: ["ANC", "7 + 28 h", "IP54"],
    specs: [
      ["Tipo", "In-ear true wireless"],
      ["Cancelación de ruido", "Activa"],
      ["Batería", "7 h (+28 h estuche)"],
      ["Carga rápida", "5 min = 1 h"],
      ["Conexión", "Bluetooth 5.3"],
      ["Resistencia", "IP54"],
      ["Peso", "5 g cada uno"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Auriculares", "Estuche de carga", "Gomas S, M y L", "Cable USB-C"],
  },
  {
    id: "mini",
    nombre: "Nodo Mini",
    marca: "Nodo",
    categoria: "Auriculares",
    precio: 54999,
    imagen: img("buds-mini-negro"),
    alt: "Auriculares in-ear negros en su estuche abierto",
    detalle: "Negro",
    rating: 4.2,
    opiniones: 267,
    stock: true,
    entrega: 2,
    destacados: ["6 + 24 h", "IPX4", "Liviano"],
    specs: [
      ["Tipo", "In-ear true wireless"],
      ["Cancelación de ruido", "No"],
      ["Batería", "6 h (+24 h estuche)"],
      ["Conexión", "Bluetooth 5.3"],
      ["Resistencia", "IPX4"],
      ["Peso", "4 g cada uno"],
      ["Garantía", "6 meses"],
    ],
    caja: ["Auriculares", "Estuche de carga", "Cable USB-C"],
  },
  {
    id: "tubo-20",
    nombre: "Sónica Tubo 20",
    marca: "Sónica",
    categoria: "Parlantes",
    precio: 129999,
    imagen: img("parlante-tubo-azul"),
    alt: "Parlante portátil cilíndrico azul con correa",
    detalle: "Azul",
    rating: 4.8,
    opiniones: 204,
    stock: true,
    entrega: 1,
    destacados: ["20 W", "16 h", "IP67"],
    specs: [
      ["Potencia", "20 W RMS"],
      ["Batería", "16 h"],
      ["Resistencia", "IP67, flota"],
      ["Conexión", "Bluetooth 5.3"],
      ["Peso", "540 g"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Parlante", "Cable USB-C", "Correa desmontable"],
  },
  {
    id: "home-mini",
    nombre: "Vektra Home Mini",
    marca: "Vektra",
    categoria: "Parlantes",
    precio: 159999,
    imagen: img("parlante-home-gris"),
    alt: "Parlante inteligente gris de tela con anillo de luz azul",
    detalle: "Gris",
    rating: 4.5,
    opiniones: 96,
    stock: true,
    entrega: 2,
    destacados: ["30 W", "Wi-Fi", "Asistente de voz"],
    specs: [
      ["Potencia", "30 W RMS"],
      ["Conexión", "Wi-Fi + Bluetooth 5.2"],
      ["Asistente de voz", "Sí, en español"],
      ["Alimentación", "A red (220 V)"],
      ["Peso", "1,1 kg"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Parlante", "Fuente de alimentación"],
  },
  {
    id: "book-14",
    nombre: "Vektra Book 14",
    marca: "Vektra",
    categoria: "Notebooks",
    precio: 1299999,
    precioAnterior: 1449999,
    imagen: img("notebook-book-14"),
    alt: "Notebook plateada de 14 pulgadas abierta con fondo de pantalla azul",
    detalle: "Plata",
    rating: 4.7,
    opiniones: 88,
    stock: true,
    entrega: 2,
    destacados: ['14" 2.2K', "16 GB", "512 GB"],
    specs: [
      ["Pantalla", '14" IPS 2.2K'],
      ["Procesador", "8 núcleos, hasta 4,4 GHz"],
      ["Memoria RAM", "16 GB"],
      ["Almacenamiento", "512 GB SSD"],
      ["Gráficos", "Integrados"],
      ["Batería", "14 h"],
      ["Peso", "1,3 kg"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Notebook", "Cargador USB-C 65 W"],
  },
  {
    id: "pro-16",
    nombre: "Nodo Pro 16",
    marca: "Nodo",
    categoria: "Notebooks",
    precio: 2099999,
    imagen: img("notebook-pro-16"),
    alt: "Notebook grafito de 16 pulgadas abierta con fondo de pantalla violeta",
    detalle: "Grafito",
    rating: 4.9,
    opiniones: 54,
    stock: true,
    entrega: 3,
    destacados: ['16" OLED', "32 GB", "GPU 8 GB"],
    specs: [
      ["Pantalla", '16" OLED 3.2K 120 Hz'],
      ["Procesador", "12 núcleos, hasta 5,0 GHz"],
      ["Memoria RAM", "32 GB"],
      ["Almacenamiento", "1 TB SSD"],
      ["Gráficos", "Dedicados 8 GB"],
      ["Batería", "12 h"],
      ["Peso", "1,9 kg"],
      ["Garantía", "24 meses"],
    ],
    caja: ["Notebook", "Cargador 140 W", "Funda"],
  },
  {
    id: "x5",
    nombre: "Kairo X5",
    marca: "Kairo",
    categoria: "Celulares",
    precio: 699999,
    precioAnterior: 799999,
    imagen: img("celular-x5-azul"),
    alt: "Celular azul visto de frente y de dorso, con doble cámara",
    detalle: "Azul · 256 GB",
    rating: 4.6,
    opiniones: 402,
    stock: true,
    entrega: 1,
    destacados: ['6,4" 120 Hz', "256 GB", "50 MP"],
    specs: [
      ["Pantalla", '6,4" AMOLED 120 Hz'],
      ["Procesador", "8 núcleos"],
      ["Memoria RAM", "8 GB"],
      ["Almacenamiento", "256 GB"],
      ["Cámara", "50 + 12 MP"],
      ["Batería", "4.800 mAh"],
      ["5G", "Sí"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Celular", "Cable USB-C", "Funda transparente"],
  },
  {
    id: "neo",
    nombre: "Nodo Neo",
    marca: "Nodo",
    categoria: "Celulares",
    precio: 1149999,
    imagen: img("celular-neo-grafito"),
    alt: "Celular grafito visto de frente y de dorso, con pantalla verde",
    detalle: "Grafito · 512 GB",
    rating: 4.8,
    opiniones: 173,
    stock: true,
    entrega: 2,
    destacados: ['6,7" OLED', "512 GB", "200 MP"],
    specs: [
      ["Pantalla", '6,7" OLED 120 Hz'],
      ["Procesador", "8 núcleos, gama alta"],
      ["Memoria RAM", "12 GB"],
      ["Almacenamiento", "512 GB"],
      ["Cámara", "200 + 50 + 12 MP"],
      ["Batería", "5.000 mAh"],
      ["5G", "Sí"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Celular", "Cable USB-C"],
  },
  {
    id: "watch-s",
    nombre: "Kairo Watch S",
    marca: "Kairo",
    categoria: "Relojes",
    precio: 249999,
    imagen: img("reloj-watch-s"),
    alt: "Reloj inteligente negro con pantalla de actividad",
    detalle: "Negro",
    rating: 4.5,
    opiniones: 131,
    stock: true,
    entrega: 1,
    destacados: ["GPS", "7 días", "5 ATM"],
    specs: [
      ["Pantalla", '1,9" AMOLED'],
      ["Batería", "7 días"],
      ["GPS", "Sí, integrado"],
      ["Resistencia", "5 ATM"],
      ["Sensores", "Ritmo cardíaco, SpO2, sueño"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Reloj", "Malla de silicona", "Base de carga"],
  },
  {
    id: "fit-3",
    nombre: "Sónica Fit 3",
    marca: "Sónica",
    categoria: "Relojes",
    precio: 119999,
    imagen: img("reloj-fit-blanco"),
    alt: "Reloj inteligente blanco con pantalla de pasos",
    detalle: "Blanco",
    rating: 4.3,
    opiniones: 88,
    stock: true,
    entrega: 3,
    destacados: ["12 días", "5 ATM", "Liviano"],
    specs: [
      ["Pantalla", '1,6" AMOLED'],
      ["Batería", "12 días"],
      ["GPS", "No (usa el del celular)"],
      ["Resistencia", "5 ATM"],
      ["Sensores", "Ritmo cardíaco, sueño"],
      ["Garantía", "6 meses"],
    ],
    caja: ["Reloj", "Cable de carga magnético"],
  },
  {
    id: "tab-11",
    nombre: "Vektra Tab 11",
    marca: "Vektra",
    categoria: "Tablets",
    precio: 599999,
    imagen: img("tablet-tab-11"),
    alt: "Tablet de 11 pulgadas con lápiz óptico al lado",
    detalle: "Gris · 256 GB",
    rating: 4.6,
    opiniones: 77,
    stock: true,
    entrega: 2,
    destacados: ['11" 120 Hz', "Lápiz incluido", "256 GB"],
    specs: [
      ["Pantalla", '11" 2.5K 120 Hz'],
      ["Procesador", "8 núcleos"],
      ["Memoria RAM", "8 GB"],
      ["Almacenamiento", "256 GB"],
      ["Batería", "10 h"],
      ["Peso", "480 g"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Tablet", "Lápiz óptico", "Cargador 33 W"],
  },
  {
    id: "key-tkl",
    nombre: "Nodo Key TKL",
    marca: "Nodo",
    categoria: "Accesorios",
    precio: 89999,
    imagen: img("teclado-key-tkl"),
    alt: "Teclado mecánico compacto grafito con dos teclas azules",
    detalle: "Grafito",
    rating: 4.7,
    opiniones: 245,
    stock: true,
    entrega: 1,
    destacados: ["Mecánico", "Inalámbrico", "200 h"],
    specs: [
      ["Tipo", "Mecánico TKL (sin numérico)"],
      ["Switches", "Lineales, hot-swap"],
      ["Conexión", "USB-C, Bluetooth y 2,4 GHz"],
      ["Batería", "200 h"],
      ["Peso", "820 g"],
      ["Garantía", "12 meses"],
    ],
    caja: ["Teclado", "Receptor 2,4 GHz", "Cable USB-C", "Extractor de teclas"],
  },
];

export const porId: Record<string, ProductoTech> = Object.fromEntries(productos.map((p) => [p.id, p]));
export const categorias: Categoria[] = ["Auriculares", "Parlantes", "Notebooks", "Celulares", "Relojes", "Tablets", "Accesorios"];
export const marcas: Marca[] = ["Nodo", "Kairo", "Sónica", "Vektra"];

export const config: ConfigTienda = {
  nombre: "Voltio",
  envioGratisDesde: 99999,
  cuotasSinInteres: 12,
  prefijoPedido: "VT",
  local: "Sucursal Voltio Nueva Córdoba",
  envios: [
    { id: "estandar", nombre: "Envío estándar", detalle: "Llega el {fecha}", dias: 3, precio: 8999, bonificable: true },
    { id: "express", nombre: "Envío express", detalle: "Llega el {fecha}, antes de las 21 h", dias: 1, precio: 14999 },
    { id: "retiro", nombre: "Retiro en sucursal", detalle: "Listo el {fecha} desde las 10 h", dias: 1, precio: 0, retiro: true },
  ],
};
