import type { ConfigTienda, ProductoCarrito } from "../shared/tipos";

export type Categoria = "Remeras" | "Abrigos" | "Pantalones" | "Calzado" | "Accesorios";

export type ProductoUrbano = ProductoCarrito & {
  categoria: Categoria;
  color: string;
  talles: string[];
  /** Talles sin stock. */
  sinStock?: string[];
  agotado?: boolean;
  nuevo?: boolean;
  /** Tipo de tabla en la guía de talles. */
  guia: "superior" | "inferior" | "calzado" | null;
  descripcion: string;
  materiales: string;
};

const img = (n: string) => `/demos/ecommerce/urbano/${n}.webp`;
const ROPA = ["S", "M", "L", "XL", "XXL"];
const CALZADO = ["38", "39", "40", "41", "42", "43", "44"];

export const productos: ProductoUrbano[] = [
  {
    id: "remera-pampa",
    nombre: "Remera Pampa",
    precio: 38900,
    imagen: img("remera-pampa-negra"),
    alt: "Remera oversize negra con estampa PAMPA en verde ácido",
    detalle: "Negro",
    color: "Negro",
    categoria: "Remeras",
    talles: ROPA,
    sinStock: ["S"],
    guia: "superior",
    descripcion: "Oversize de hombro caído y cuello de ribb grueso. Estampa frontal en tinta al agua que no se cuartea con los lavados.",
    materiales: "100 % algodón peinado 24/1, 210 g. Lavar del revés en frío.",
  },
  {
    id: "remera-sol",
    nombre: "Remera Sol",
    precio: 36900,
    imagen: img("remera-sol-hueso"),
    alt: "Remera color hueso con gran estampa negra de sol y la palabra PAMPA CLUB",
    detalle: "Hueso",
    color: "Hueso",
    categoria: "Remeras",
    talles: ROPA,
    guia: "superior",
    descripcion: "La remera del club: sol negro gigante en el frente y calce recto, un poco más largo atrás.",
    materiales: "100 % algodón peinado 24/1, 200 g. Estampa serigráfica.",
  },
  {
    id: "remera-acida",
    nombre: "Remera Básica Ácida",
    precio: 29900,
    imagen: img("remera-basica-acida"),
    alt: "Remera básica verde ácido con logo chico en el pecho",
    detalle: "Verde ácido",
    color: "Verde ácido",
    categoria: "Remeras",
    talles: ROPA,
    nuevo: true,
    guia: "superior",
    descripcion: "El básico que no es básico: color ácido teñido en prenda y logo bordado en el pecho.",
    materiales: "100 % algodón, 180 g. Teñido en prenda: puede variar levemente el tono.",
  },
  {
    id: "hoodie-acido",
    nombre: "Hoodie Club Ácido",
    precio: 84900,
    imagen: img("hoodie-acido"),
    alt: "Buzo con capucha verde ácido, bolsillo canguro y cordones blancos",
    detalle: "Verde ácido",
    color: "Verde ácido",
    categoria: "Abrigos",
    talles: ROPA,
    sinStock: ["XXL"],
    nuevo: true,
    guia: "superior",
    descripcion: "Frisa pesada, capucha doble y bolsillo canguro. El buzo que te ponés todo el invierno.",
    materiales: "80 % algodón, 20 % poliéster, frisa invisible 380 g.",
  },
  {
    id: "hoodie-noche",
    nombre: "Hoodie Noche",
    precio: 84900,
    imagen: img("hoodie-negro"),
    alt: "Buzo con capucha negro con la palabra NOCHE estampada en blanco",
    detalle: "Negro",
    color: "Negro",
    categoria: "Abrigos",
    talles: ROPA,
    guia: "superior",
    descripcion: "Negro profundo con estampa blanca de alto relieve. Puños y cintura de ribb.",
    materiales: "80 % algodón, 20 % poliéster, frisa invisible 380 g.",
  },
  {
    id: "buzo-club",
    nombre: "Buzo Club Gris",
    precio: 72900,
    imagen: img("crew-gris"),
    alt: "Buzo cuello redondo gris melange con la palabra CLUB en negro",
    detalle: "Gris melange",
    color: "Gris melange",
    categoria: "Abrigos",
    talles: ROPA,
    agotado: true,
    guia: "superior",
    descripcion: "Cuello redondo, calce boxy. Volvió y se fue en un día: anotate para la reposición.",
    materiales: "Algodón y poliéster reciclado, frisa 340 g.",
  },
  {
    id: "rompevientos",
    nombre: "Rompevientos Franja",
    precio: 119900,
    imagen: img("campera-rompevientos"),
    alt: "Campera rompevientos negra con una franja horizontal verde ácido y cierre central",
    detalle: "Negro / ácido",
    color: "Negro con franja ácida",
    categoria: "Abrigos",
    talles: ROPA,
    sinStock: ["S", "M"],
    guia: "superior",
    descripcion: "Nylon liviano repelente al agua, forrería de red y franja reflectiva para la noche.",
    materiales: "Exterior 100 % poliamida. Forro de red de poliéster.",
  },
  {
    id: "cargo-arena",
    nombre: "Cargo Arena",
    precio: 89900,
    imagen: img("cargo-arena"),
    alt: "Pantalón cargo color arena con bolsillos laterales",
    detalle: "Arena",
    color: "Arena",
    categoria: "Pantalones",
    talles: ["38", "40", "42", "44", "46"],
    guia: "inferior",
    descripcion: "Gabardina pesada, calce recto amplio y seis bolsillos. Botamanga con cordón para ajustar.",
    materiales: "98 % algodón, 2 % elastano. Gabardina 12 oz.",
  },
  {
    id: "cargo-negro",
    nombre: "Cargo Negro",
    precio: 89900,
    imagen: img("cargo-negro"),
    alt: "Pantalón cargo negro con bolsillos laterales sobre fondo verde ácido",
    detalle: "Negro",
    color: "Negro",
    categoria: "Pantalones",
    talles: ["38", "40", "42", "44", "46"],
    agotado: true,
    guia: "inferior",
    descripcion: "El cargo de siempre en negro total. Agotado: vuelve en el próximo ingreso.",
    materiales: "98 % algodón, 2 % elastano. Gabardina 12 oz.",
  },
  {
    id: "zapa-pista",
    nombre: "Zapatilla Pista Blanca",
    precio: 139900,
    imagen: img("zapatilla-pista"),
    alt: "Zapatilla urbana blanca de caña baja con franjas y puntera negras",
    detalle: "Blanco / negro",
    color: "Blanco con detalles negros",
    categoria: "Calzado",
    talles: CALZADO,
    sinStock: ["38", "44"],
    guia: "calzado",
    descripcion: "Caña baja de cuero vacuno con franjas laterales, plantilla de memoria y suela de caucho cosida.",
    materiales: "Capellada de cuero. Suela de caucho natural. Hecha en Argentina.",
  },
  {
    id: "zapa-noche",
    nombre: "Zapatilla Pista Noche",
    precio: 139900,
    imagen: img("zapatilla-acida"),
    alt: "Zapatilla urbana negra con franjas y puntera verde ácido",
    detalle: "Negro / ácido",
    color: "Negro con detalles ácidos",
    categoria: "Calzado",
    talles: CALZADO,
    nuevo: true,
    guia: "calzado",
    descripcion: "La Pista en versión nocturna: gamuza negra y detalles ácidos que se ven de lejos.",
    materiales: "Capellada de gamuza. Suela de caucho natural. Hecha en Argentina.",
  },
  {
    id: "gorra-pampa",
    nombre: "Gorra Pampa",
    precio: 29900,
    imagen: img("gorra-negra"),
    alt: "Gorra negra de seis paneles con parche verde ácido que dice PAMPA",
    detalle: "Negro",
    color: "Negro",
    categoria: "Accesorios",
    talles: ["Único"],
    guia: null,
    descripcion: "Seis paneles, visera curva y cierre de hebilla metálica. Parche tejido al frente.",
    materiales: "100 % algodón gabardina. Talle único ajustable.",
  },
  {
    id: "gorra-hueso",
    nombre: "Gorra Hueso",
    precio: 29900,
    imagen: img("gorra-hueso"),
    alt: "Gorra color hueso con visera negra y logo bordado",
    detalle: "Hueso / negro",
    color: "Hueso con visera negra",
    categoria: "Accesorios",
    talles: ["Único"],
    agotado: true,
    guia: null,
    descripcion: "Bicolor con logo bordado. Se agotó en el drop anterior.",
    materiales: "100 % algodón gabardina. Talle único ajustable.",
  },
  {
    id: "rinonera",
    nombre: "Riñonera Ruta",
    precio: 34900,
    imagen: img("rinonera-negra"),
    alt: "Riñonera negra con correa, cierre y etiqueta verde ácido con la palabra PAMPA",
    detalle: "Negro",
    color: "Negro",
    categoria: "Accesorios",
    talles: ["Único"],
    guia: null,
    descripcion: "Entra celular, billetera y llaves. Correa regulable para usarla cruzada o en la cintura.",
    materiales: "Cordura 600D repelente al agua. Cierre reforzado.",
  },
  {
    id: "medias-club",
    nombre: "Medias Club x2",
    precio: 15900,
    imagen: img("medias-pack"),
    alt: "Par de medias largas blancas con dos franjas negras",
    detalle: "Pack de 2 pares",
    color: "Blanco con franjas",
    categoria: "Accesorios",
    talles: ["35-39", "40-44"],
    guia: null,
    descripcion: "Caña alta, puño acanalado y planta con toalla. Pack de dos pares.",
    materiales: "75 % algodón, 22 % poliamida, 3 % elastano.",
  },
];

export const porId: Record<string, ProductoUrbano> = Object.fromEntries(productos.map((p) => [p.id, p]));

export const categorias: Categoria[] = ["Remeras", "Abrigos", "Pantalones", "Calzado", "Accesorios"];

export const looks = [
  { id: "01", titulo: "Calle", imagen: img("lookbook-01"), alt: "Look 01: hoodie ácido, cargo negro, gorra negra y zapatillas blancas", piezas: ["hoodie-acido", "cargo-negro", "gorra-pampa", "zapa-pista"] },
  { id: "02", titulo: "Verano", imagen: img("lookbook-02"), alt: "Look 02: remera negra, cargo arena, riñonera y zapatillas negras", piezas: ["remera-pampa", "cargo-arena", "rinonera", "zapa-noche"] },
  { id: "03", titulo: "Noche", imagen: img("lookbook-03"), alt: "Look 03: rompevientos con franja ácida, gorra hueso y medias", piezas: ["rompevientos", "gorra-hueso", "medias-club"] },
];

export const guias = {
  superior: {
    titulo: "Remeras y abrigos",
    columnas: ["Talle", "Pecho (cm)", "Largo (cm)", "Manga (cm)"],
    filas: [
      ["S", "54", "70", "22"],
      ["M", "57", "72", "23"],
      ["L", "60", "74", "24"],
      ["XL", "63", "76", "25"],
      ["XXL", "66", "78", "26"],
    ],
    consejo: "El calce es oversize. Si te gusta más al cuerpo, elegí un talle menos.",
  },
  inferior: {
    titulo: "Pantalones",
    columnas: ["Talle", "Cintura (cm)", "Cadera (cm)", "Largo (cm)"],
    filas: [
      ["38", "76", "100", "102"],
      ["40", "80", "104", "103"],
      ["42", "84", "108", "104"],
      ["44", "88", "112", "105"],
      ["46", "92", "116", "106"],
    ],
    consejo: "Medí un pantalón que te quede bien, apoyado en una mesa, y compará la cintura.",
  },
  calzado: {
    titulo: "Calzado",
    columnas: ["Talle AR", "Largo del pie (cm)", "Equivale US"],
    filas: [
      ["38", "24,5", "6,5"],
      ["39", "25", "7"],
      ["40", "25,5", "8"],
      ["41", "26,5", "8,5"],
      ["42", "27", "9,5"],
      ["43", "28", "10"],
      ["44", "28,5", "11"],
    ],
    consejo: "Horma normal. Si estás entre dos talles, elegí el más grande.",
  },
} as const;

export const config: ConfigTienda = {
  nombre: "Pampa Club",
  envioGratisDesde: 150000,
  cuotasSinInteres: 6,
  prefijoPedido: "PC",
  etiquetaVariante: "Talle",
  local: "Showroom Pampa Club, barrio Güemes (Córdoba)",
  envios: [
    { id: "domicilio", nombre: "Envío a domicilio", detalle: "Llega el {fecha}", dias: 4, precio: 7900, bonificable: true },
    { id: "moto", nombre: "Moto en Córdoba Capital", detalle: "Llega el {fecha}, de 14 a 20 h", dias: 1, precio: 4900 },
    { id: "retiro", nombre: "Retiro en el showroom", detalle: "Listo para retirar el {fecha}", dias: 1, precio: 0, retiro: true },
  ],
};
